description = 'Polariser devices in the SINQ AMOR.'

display_order = 30

pvprefix = 'SQ:AMOR:turboPmac1:'
picoprefix = 'SQ:AMOR:pico:'

includes = ['constants']

devices = dict(
    pz1 = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Polariser Z-translation 1',
        motorpv = pvprefix + 'pz1',
        visibility = ('metadata', 'namespace'),
    ),
    pz2 = device('nicos_sinq.devices.epics.sinqmotor_deprecated.SinqMotor',
        description = 'Polariser Z-translation 2',
        motorpv = pvprefix + 'pz2',
        visibility = ('metadata', 'namespace'),
    ),
    polarisation = device('nicos.devices.generic.switcher.MultiSwitcher',
        description = 'move polariser in or out of the beam',
        moveables = ['pz1', 'pz2', 'spinflipper_amp'],
        mapping = {
            'on': [13.5, 12.0, 0.],
            'off': [91.3, 90.8, 0.],
        },
        precision = [None],
        visibility = ('devlist', 'metadata', 'namespace'),
    ),
    spinflipper_amp = device('nicos_sinq.devices.epics.generic.WindowMoveable',
                             description = 'Spin Flipper Amplitude',
                             writepv = picoprefix + 'AMP',
                             readpv = picoprefix + 'AMP_RBV',
                             abslimits = (0, 5),
                             precision = .01,
                             visibility = ('metadata', 'namespace'),
                             ),
    spinflipper_freq = device('nicos_sinq.devices.epics.generic.WindowMoveable',
                              description = 'Spin Flipper Frequency',
                              writepv = picoprefix + 'FREQ',
                              readpv = picoprefix + 'FREQ_RBV',
                              abslimits = (0, 300000),
                              precision = 1,
                              visibility = ('metadata', 'namespace'),
                              ),
    polarization_defs = device('nicos_sinq.amor.devices.polarizer_defs.AmorPolarizer',
                               description = 'encoding of polarisation',
                               pz1 = 'pz1',
                               pz2 = 'pz2',
                               spinflipper_amp = 'spinflipper_amp',
                               polarizer_lift_1_fom = 'polarizer_lift_1_fom',
                               polarizer_lift_2_fom = 'polarizer_lift_2_fom',
                               polarizer_lift_1_pol = 'polarizer_lift_1_pol',
                               polarizer_lift_2_pol = 'polarizer_lift_2_pol',
                               spin_flipper_current_p = 'spin_flipper_current_p',
                               unit = '',
                               visibility = ('metadata', 'namespace'),
                               ),
    polarization_config_label = device('nicos.devices.generic.ParamDevice',
                                       description = 'label of polarisation configuration for hdf file: 0=undef, 1=unpol, 2=plus, 3=minus',
                                       device = 'polarization_defs',
                                       parameter = 'polconfiglabel',
                                       abslimits = (0, 9),
                                       unit = '',
                                       copy_status = True,
                                       visibility = ('metadata', 'namespace'),
                                       ),
    polarization_config = device('nicos.devices.generic.ParamDevice',
                                 description = 'switch polarisation configuration',
                                 device = 'polarization_defs',
                                 parameter = 'polconfig',
                                 abslimits = (0, 9),
                                 unit = '',
                                 copy_status = True,
                                 visibility = ('metadata', 'namespace'),
                                 ),
    #pol_symbol = device('nicos.devices.generic.ParamDevice',
    #                 description = 'indicator for the polarization configuration',
    #                 device = 'base_defs',
    #                 parameter = 'polsymbol',
    #                 unit = '',
    #                 copy_status = True,
    #                 visibility = ('metadata', 'namespace'),
    #                 ),
    )

startupcode = '''
spinflipper_freq.start(140200)
'''
